[package]
name = "sockdeez"
version = "0.1.0"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2021"

[[example]]
name = "echo_server"
path = "examples/echo_server.rs"

[dependencies]
tokio = { version = "1.26.0",  default-features = false, features = ["io-util"] }

[build-dependencies]
cc = "1.0"

[dev-dependencies]
# examples
tokio = { version = "1.25.0", features = ["full"] }
deno_core = "0.175.0"
deno_ops = "0.53.0"
rand = "0.8.4"
base64 = "0.21.0"
sha1 = "0.10.5"
# bench
criterion = "0.4.0"

[[bench]]
name = "unmask"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
