[package]
name = "sockdeez"
version = "0.1.0"
authors = ["Divy Srivastava <dj.srivastava23@gmail.com>"]
edition = "2021"

[lib]
path = "lib.rs"

[[example]]
name = "echo_server"
path = "examples/echo_server.rs"

[dependencies]
# tokio = { version = "1.26.0", features = ["rt", "net"] }
tokio = { version = "1.25.0", features = ["full"] }
base64 = "0.21.0"
sha1 = "0.10.5"
rand = "0.8.4"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
deno_core = "0.175.0"
deno_ops = "0.53.0"
criterion = "0.4.0"
rand = "0.8.4"

[[bench]]
name = "unmask"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
